[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "atk",
  "atkmm",
  "cups",
  "gtk3",
  "libdrm",
  "libxkbcommon",
  "libxcomposite",
  "libxdamage",
  "libxfixes",
  "libxrandr",
  "gbm",
  "pango",
  "cairo"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium"
]

[start]
cmd = "python main.py"
